podTemplate(label: 'scale-canary-replicas',
  containers: [
    containerTemplate(name: 'kubectl', image: 'jorgeacetozi/kubectl:1.7.0', ttyEnabled: true, command: 'cat')
  ])
{
  node ('scale-canary-replicas') {
    stage('Scale the number of replicas for the Canary deployment') {
      container("kubectl") {
        sh """
          kubectl scale deployment notepad-deployment-canary --replicas ${REPLICAS}
          kubectl rollout status deployment notepad-deployment-canary
          kubectl label pods -l track=canary env=production --overwrite=true
          sleep 10
          kubectl get service notepad-service-canary
          kubectl get endpoints notepad-service-canary
        """
      }
    }
  }
}
