apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  labels:
    app: notepad
spec:
  selector:
    app: jenkins
    role: master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
    name: ui
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  labels:
    app: notepad
spec:
  selector:
    app: jenkins
    role: master
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: slaves
