apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
  labels:
    app: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31010
    name: ui
  type: NodePort
